version: "3.9"

services:
  api:
    build: .
    container_name: univercity_api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - castlemock
    environment:
      - MONGO_URL=mongodb://mongo:27017
    restart: always

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always

  castlemock:
    image: castlemock/castlemock
    container_name: castlemock
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
    volumes:
      - ./castlemock_data_persistent:/root/.castlemock
    restart: unless-stopped
